== MLBParks backend application

This application is a backend that provides geolocation information about MLBParks. It is a JEE Application built on JBoss EAP 7.0.

=== Prerequisites

* The information is stored in a MongoDB. Therefore a MongoDB instance with persistent storage needs to be set up.
* The following Environment Variables need to be configured:
** DB_HOST
** DB_PORT
** DB_USER
** DB_PASSWORD
** DB_NAME
// * Additional properties:
// ** db.properties: db.user=${MONGODB_USER}\ndb.password=${MONGODB_PASSWORD}\ndb.name=${MONGODB_DATABASE}
// ** application.properties: spring.data.mongodb.uri=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_APPLICATION_NAME}:27017/${MONGODB_DATABASE}
* After installation the following URL loads the default data:
** <route_url>/ws/data/load
* The running service maintains a REST endpoint to be discovered at <route_url>/ws/info/
* There is a health check endpoint at <route_url>/healthz

=== Hints

* Use the JBoss EAP 7.0 S2I builder image
* You can set MAVEN_MIRROR_URL as a build environment variable to point to a local artifact repository
* You may want to set up a post deployment hook to automatically load the data after deployment
* You may want to create readiness and liveness probes.
