== Parksmap application

This application is a frontend web and gateway to backend services that provide geolocation data on services. It is a SpringBoot application.

=== Installation

The application needs to interact with OpenShift's API. Therefore you will need to provide *view* permissions to the *default* ServiceAccount of your project.

// Assuming you're using the project <parks>:
//
// [source,bash]
// ----
// oc new-project parks
// oc policy add-role-to-user view system:serviceaccount:parks:default
// ----

=== Hints

* Use the OpenJDK 1.8 S2I builder image
* You can set MAVEN_MIRROR_URL as a build environment variable to point to a local artifact repository
* You may want to create readiness and liveness probes.

=== Background Information

==== Backends

Backend *services* require to have an specific annotation to be discovered:

----
type: parksmap-backend
----

Every backend should provide an endpoint located at */ws/info* that will provide link:src/main/java/com/openshift/evg/roadshow/rest/gateway/model/Backend.java[Backend] information.

Here you can find 2 sample implementations:

* Springboot:

[source,java]
----
@RequestMapping("/ws/info")
@RestController
public class BackendController{

    @RequestMapping(method = RequestMethod.GET, value = "/", produces = "application/json")
    public Backend get() {
        return new Backend(....);
    }
}
----

* JEE:

[source,java]
----
@Path("/ws/info")
public class BackendController{
    @GET
    @Path("/")
    @Produces(MediaType.APPLICATION_JSON)
    public Backend get() {
        return new Backend(....);
    }
}
----

==== Use
Once the application has been deployed, you can manually register/unregister a backend:

==== Test locally
This application can be run locally against while having the backend services running on a local openshift instance (all-in-one, oc cluster up or CDK).

==== Run it
To run the application, you should just:

[source]
----
mvn clean install spring-boot:run
----

Backends will be registered if they are deployed or when deployed, and unregistered when undeployed.

But you can test registration/unregistration manually.

==== Register
To register a backend:

----
curl -i http://parksviewer.apps.127.0.0.1.xip.io/ws/backends/register?service=nationalparks-roadshow.127.0.0.1.xip.io
curl -i http://parksviewer.apps.127.0.0.1.xip.io/ws/backends/register?service=mlbparks-roadshow.127.0.0.1.xip.io
----

==== Unregister
To unregister a backend:

----
curl -i http://parksviewer.apps.127.0.0.1.xip.io/ws/backends/unregister?service=nationalparks-roadshow.127.0.0.1.xip.io
curl -i http://parksviewer.apps.127.0.0.1.xip.io/ws/backends/unregister?service=mlbparks-roadshow.127.0.0.1.xip.io
----

==== List backend
To list available backends:

----
curl -i http://parksviewer.apps.127.0.0.1.xip.io/ws/backends/list
----
